/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ReadlistImport } from './routes/readlist'
import { Route as IndexImport } from './routes/index'
import { Route as PopularIndexImport } from './routes/popular/index'
import { Route as LoginIndexImport } from './routes/login/index'

// Create/Update Routes

const ReadlistRoute = ReadlistImport.update({
  path: '/readlist',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PopularIndexRoute = PopularIndexImport.update({
  path: '/popular/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/readlist': {
      id: '/readlist'
      path: '/readlist'
      fullPath: '/readlist'
      preLoaderRoute: typeof ReadlistImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/popular/': {
      id: '/popular/'
      path: '/popular'
      fullPath: '/popular'
      preLoaderRoute: typeof PopularIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ReadlistRoute,
  LoginIndexRoute,
  PopularIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/readlist",
        "/login/",
        "/popular/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/readlist": {
      "filePath": "readlist.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/popular/": {
      "filePath": "popular/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
